### ISSUE TITLE
OPD Profile Page Overview Tab

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-opd#10]
The OPD profile should be similar to the ANC profile page. It should only have the overview and Contact Tab

- [x] The Overview tab should have the below sections as per the data dictionary Check-In Worksheet
![Screenshot_1569399659](https://user-images.githubusercontent.com/18394882/65582872-e3aeb480-df86-11e9-98f3-ce0b855914e4.png)

- [ ] 

- [x] Pregnancy status group should have the below information as per data dictionary and should only be shown if the person is a female
Pregancy Status {Positive/Negative/Unknown}

- [x] HIV Details group should have:
Previously tested for HIV {Yes/No}
Previous HIV Status {Positive/Negative/Unknown}
Patient on ART {Yes/No}
Current HIV Status {Positive/Negative/Unknown/Not Done

- [x] Latest Visit {Date} group should have
Visit Type {New/Referral/Revisit}
Previous Appointment {Yes/No}
Date of Appointment {Date}
Appointment to Visit Duration {Calculation of Visit Date-Appointment Date}

- [x] Note on OPD is that this information is from the most recent event as this information is expected to be recorded on every visit

**Comment by rowo** [comment]
So just reviewing this @hmakandi @ekigamba. Seems like the profile needs to work for multiple states beyond "male and female currently checked-in" as described above. This view should also support profiles for (1) registered (no prior visits), (2) pre check-in (previously visited), and possibly (3) recently diagnosed/treated (though this can shared the view from (2)). We'll also need access to either the "check-in" and "diagnose & treat" buttons.

So I'm defining this out now and will post below shortly. @ekigamba For feasibility sake, should we try to keep the information shown consistent no matter the state of the user (only difference being hiding pregnancy status if male)? Is it "easy" to hide groups if the information doesn't exist?

**Comment by rowo** [comment]
@hmakandi @ekigamba Also thinking through this more, the thing we did with the CHW app was to make the profile consistent for a user no matter how the user navigated to the client (the profile was modular). With our timeline of the FHW app on Malawi, that's probably not even feasible. I  mentioned this early in this project and just making a note here about that.

This issue implies that a child's OPD profile will be OPD specific. Same for an ANC person. Which then implies everyone needs a link to their module-specific profiles if they exist. Also since we're using the OPD profile as All Clients, these profiles will need to support the workflows for adding clients to other modules — for example if Pregnancy Test = Positive, is there at least a prompt to add them to ANC? 

@mberg not sure if you have opinions on the above

**Comment by rowo** [comment]
Some solutions:
1) Build a modular facility app profile that will be used by new modules we’re building (maternity, OPD, whatever else), knowing that at some point the content from the ZEIR child and WHO ANC profiles will need to be adapted to it.
2) Have individual profiles then do an overlaid profile switcher button (extended FAB) that pulls up the other modules the user is in — that way we can add it to the existing child and anc profiles. Long term we could potentially shift to this if each module has very different and detailed information as a replacement for tabs.

**Comment by ekigamba** [comment]
@rowo

> For feasibility sake, should we try to keep the information shown consistent no matter the state of the user (only difference being hiding pregnancy status if male)? Is it "easy" to hide groups if the information doesn't exist?

I also agree. We are currently hiding the pregnancy state if the patient is a male

**Comment by rowo** [comment]
Ok just to summarize, there are two items we should address:

1) Will our ultimate goal for the facility app to have consistent medical profiles no matter what register the user is coming from (i.e. an ANC client with Malaria will have the same profile layout no matter if they come from ANC or Malaria registers). This is how the CHW app works, which perhaps made more sense there because families/households made the registers less important and there was much less unique clinical information to display. This is a product level decision that needs involvement from all internal stakeholders.
2) The OPD profile itself needs to handle multiple states. We could either change what shows based on the state or try to keep it consistent.

**Comment by rowo** [comment]
Update from the today meeting
- Pushing off decision about consistent facility profile until later. Will use some kind of profile-switcher FAB to treat existing profiles like "views". These views will need some indiction of what module they represent for that user
- Will update OPD profile to show different information at different states and use simple "hide if doesn't exist" logic

**Comment by rowo** [comment]
@hmakandi @ekigamba As a rule, since OPD is a new thing that didn't exist in OpenSRP and is unknown or fuzzy, next time kindly don't start building before finalizing requirements with myself and @mberg. Discussion with the product team should be built into the timeline for anything new or notably different from what've built before — things like this.

See [previous comment](https://github.com/OpenSRP/opensrp-client-opd/issues/10#issuecomment-539654634) for information on the register view switcher and [OPD data dictionary](https://docs.google.com/spreadsheets/d/1h2JrUCi0geT1NQm63bEicT0knKaOYe-LJ-gEFlODETc/edit#gid=331049840) for the data we're working with.

**For discussion only (i.e. not yet final)**, here's a few states and some thoughts on logic:

## New registration, male
- Registration has very basic information, but we can still show the Pregnancy Status (for females) and HIV Details sections with "unknown" answers.
- The "Registration Info" button goes to the OPD reg form
<img src="https://user-images.githubusercontent.com/1584163/66522249-fa8ef400-eaba-11e9-9676-35bd46209f98.png" width="333">

## Male profile with prev visits, not checked in
- Once this person has had an OPD visit, we'll have info on Preg Status and HIV Details. The HIV  Details uses the last HIV test result value (and any other forms that ask this across all registers). It doesn't say "previous" or "current" on the label because this user hasn't checked in yet so it's just a last known status.
<img src="https://user-images.githubusercontent.com/1584163/66522830-5443ee00-eabc-11e9-9672-d63c45c6ce8b.png" width="333">

## Female profile with prev visits, not checked in
- The female equivalent of the previous screen has the Pregnancy Status section added. This data is updated by previous OPD forms or ANC reg/close forms.
<img src="https://user-images.githubusercontent.com/1584163/66522318-2611de80-eabb-11e9-85f2-9174c9b603ca.png" width="333">

## Female profile with prev visits, checked in
- After check in, (1)the information for Pregnancy Status and HIV Details get updated with the most recent inputs, (2) a "current visit" section gets added with information on the visit type, and (3) the OPD section becomes "OPD Checked in" and the button becomes a "Diagnose & Treat" button.

<img src="https://user-images.githubusercontent.com/1584163/66522336-2d38ec80-eabb-11e9-8956-86fef00abd0c.png" width="333">

## After diagnose and treat
The profile resets back to the "Not checked in" view after the diagnose & treat form is submitted (with pertinent fields updated). The visit's forms can be found in the Visit Tab - https://github.com/OpenSRP/opensrp-client-opd/issues/11#issuecomment-540206077

**Comment by rowo** [comment]
@hmakandi Also wondering — ANC has this idea of exiting the form and coming back to it because an ANC contact can be so long. This seems similar if they are trying to fill out the form in real time (though realistically this seems like something that would be recorded at the end at one time) — which means we need to apply the "in-progress" state to the diagnose and test button/form.

**Comment by hmakandi** [comment]
@rowo Yes, true, there is an exit of the form and coming back concept. However, I do not understand the "in-progress" state... Isn't the top part where it shows OPD:CHECKED IN addressing the state? Or how else would this be addressed?

**Comment by rowo** [comment]
@hmakandi Yes, that's true on the in progress state. Checked in should work on it's own. We don't show a diagnose and treat form in progress — we just assume that everyone that has checked in is currently present and has either started their D&T form or will start it soon.

**Comment by rowo** [comment]
@hmakandi I talked to Eph and Benn and recently updated the [other issue for the Contact/Visit tab](https://github.com/OpenSRP/opensrp-client-opd/issues/11). 

For this Overview tab, I was wondering what the outstanding issues were. So far I have:
- show design for the switch register dialog
- work on additional ways to indicate which register the user is viewing

**Comment by hmakandi** [comment]
Conrfimed. Changes to check-in to just reflect scheduling information, the rest is under diagnosis and treatment.
![Screenshot_1589967821](https://user-images.githubusercontent.com/18394882/82431682-a3f98780-9a97-11ea-9a1f-2a2a4c6f0fb2.png)
