### ISSUE TITLE
OPD Profile Page Visit Tab

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-opd#11]
- [x] On the contact tab for the profile page for OPD.
![Screenshot_1569400983](https://user-images.githubusercontent.com/18394882/65586137-4fdfe700-df8c-11e9-8743-45b8b7b15583.png)

- [x] LATEST VISIT {DATE} should be a large grouping similar to the "LAST CONTACT" in the ANC profile. Under the Latest Visit Group there should be subheadings similar to the blue subheading texts {Date} in ANC profile
- [x] The sub headings should be "RECENT TESTS" , "DIAGNOSIS AND TREATMENT" and "MEDICATION AND DRUGS". On these sub-headings avoid repeating the date as it was already provided in the overarching group. The subheadings can be in the manner depicted in ANC as shown below
![Screenshot_1569402189](https://user-images.githubusercontent.com/18394882/65586251-874e9380-df8c-11e9-8ca4-0b0da3ca6fb1.png)

- [x] Latest Visit should show the most recent completed visit data

- [x] PREVIOUS VISIT is similar to the above LATEST VISIT in structure and data, though for older events/visits by the client For now, consider showing the information in a similar fashion as the LATEST VISIT with similar groupings.

**Comment by ekigamba** [comment]
@rowo Here is the state that shows the previously done visits. In OPD, this will be visits

**Comment by rowo** [comment]
@hmakandi  For ANC, [Reveal](https://github.com/OpenSRP/opensrp-client-reveal/issues/306#issuecomment-533952251), WCARO and Mastercard, in cases where we are presenting full forms back to the user, instead of reformatting the data from previous visit forms, we just linked to them filled out in their original format (with a "Save" button if editable, without if non-editable). 

We formatted the information is an easier-to-read format when we're only showing selected pieces of information like the ANC profile overview or contacts.

I think we should take the same approach for Malawi and just link to the completed forms. @ekigamba considering check in and diagnosis and treatment are two separate forms, would this mean we would need links to both? Is there anyway to combine these? If not, I think that's acceptable from a UI standpoint if it saves work since this is not a high priority interaction and just adds one extra tap.

Below is an example of how the visit tab would look. If we need to link to two separate forms, the next level would be check in and diagnosis and treatment for that individual OPD date.

![OPD-Female-Visit Tab](https://user-images.githubusercontent.com/1584163/66521296-de8a5300-eab8-11e9-9623-af0104ada589.png)

**Comment by rowo** [comment]
@ekigamba @hmakandi I had worked on this and didn't upload. From what I remember — we didn't need to link to the full form information, we wanted it all to show up on the Visit tab (just scrolls downward), and it was to reflect the information in rows 2-31 in the Diagnose and Treat form in the dictionary. So I just put it in the normal table. We need to define some light logic on how rows appear depending on answer, same as the dictionary.

<img src="https://user-images.githubusercontent.com/1584163/67486014-2c669580-f639-11e9-820e-2c977011fb0c.png" width="333">

**Comment by ekigamba** [comment]
@rowo Yea, it seems that the current register view might not be obvious. Do we have a limit on the number of summarised visits to show in this tab?

**Comment by rowo** [comment]
@ekigamba I don't think we need a limit unless you think it'll be a problem in term of loading the data. At some point, we could organize it a bit better into years, add a search, connect similar diagnosis, etc... but that seems like trying to anticipate problems that don't exist yet because this is new and nobody's going to have 20+ OPD visits across years yet.

**Comment by ekigamba** [comment]
@rowo We need a limit. Something reasonable. And probably a way of going back. Why don't we work with an estimate of the app being used for two years before any upgrades/changes that cater for practical conditions on the ground

**Comment by rowo** [comment]
@ekigamba I like the concept of saying "we should deliver products that can work without major updates for X duration". We should talk about what that means across the board at the retreat. (Though I don't know if 2 years is that number.)

Anyways, at this point, I assume we want to:
- avoid "advanced functionality" like filters or subnav
- avoid any sort of logic like if X number of entires, show it a certain way.. or if entries exist in year, show it a certain way
- keep the view as summaries without tapping further (at least for the recent visits)

My general approach with scrolling is it is not a big deal, especially on mobile. Even looking at something like Slack mobile search results (infinite scroll) or mobile mail apps — but maybe that's because they have search. 

So in terms of limit, I don't know — maybe the most recent 10 seems reasonable then it paginates (either as infinite scroll or pages of 10) after that? 

I don't think it's worth building out a way to view by year right now. For OPD seems like recent history would be the major focus.

**Comment by hmakandi** [comment]
@rowo I think the pagination with the 10 visits is a good approach for now. The thoughts invoked by @ekigamba is because when developing, the team has to develop in a way that allows easier extension and configurability by other possible projects. In our case we are not doing extensive logic, but we should develop this view as a configurable piece where if the configurations are applied as per our project context, we will show the paginated view.

**Comment by ekigamba** [comment]
Update on visits view considering that medicines & disease codes can be multiple

**Comment by hmakandi** [comment]
Confirmed and closed
![Screenshot_1589967629](https://user-images.githubusercontent.com/18394882/82431257-1b7ae700-9a97-11ea-804f-545c80f52954.png)
